        name: Run Main.java class
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name:set up java
      uses: actions/setup-java@v3
      with:java-version: '17'

      name:  compile and run
      run:
      javac Main.java
        java Main
