name: Selenium Java Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Use the version required for your project

      # Step 3: Set up browser drivers
(e.g., ChromeDriver)
      - name: Set up ChromeDriver
        uses: actions/setup-chromedriver@v1
        with:
          version: 'latest'

      # Step 4: Install Maven dependencies
      - name: Install Maven dependencies
        run: mvn install

      # Step 5: Run Selenium tests
      - name: Run Selenium tests
        run: mvn test
